version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gif
    ports:
      - '5432:5430'

  gif:
    container_name: gifFiles
    image: gif
    ports:
      - '8080:8080'
    environment:
      - server-port=9000
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/gif
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db